// <copyright file="2_t4DomainViewModelsGenerate.cs" company="marcos software">
// This file may not be redistributed in whole or significant part
// and is subject to the marcos software license.
//
// @author: Sascha Manns, s.manns@marcossoftware.com
// @copyright: 2022, marcos-software, http://www.marcos-software.de
// </copyright>




// —————————————— 
// <auto-generated> 
//	This code was auto-generated 07/18/2022 12:21:32 
//	T4 template generates viewmodel's code 
//	NOTE:T4 generated code may need additional updates/addjustments by developer in order to compile a solution.
// <auto-generated> 
// —————————————–
using System;
using System.Collections.Generic;
namespace AppLicenseserver.Domain
{

	/// <summary>
	///
	/// A License view model
	///   
	///       MANUAL UPDATES REQUIRED! 
	///       NOTE use PM console to update database with new entity : 
	///            PM>add-migration AddLicense
	///            PM>update-database
	///
	/// </summary>
	public class LicenseViewModel : BaseDomain
	{
		public System.Guid Licensenumber { get; set; }
		public bool IsActive { get; set; }
		public int ProductId { get; set; }
		public virtual ProductViewModel Product { get; set; }
		public int UserId { get; set; }
		public virtual UserViewModel User { get; set; }
	}

	/// <summary>
	///
	/// A Product view model
	///   
	///       MANUAL UPDATES REQUIRED! 
	///       NOTE use PM console to update database with new entity : 
	///            PM>add-migration AddProduct
	///            PM>update-database
	///
	/// </summary>
	public class ProductViewModel : BaseDomain
	{
		public string Name { get; set; }
		public string Description { get; set; }
		public string Version { get; set; }
		public System.DateTime ReleaseDate { get; set; }
		public bool IsReleased { get; set; }
		public bool IsActive { get; set; }
		public bool IsDeleted { get; set; }
		public virtual System.Collections.Generic.ICollection<LicenseViewModel> Licenses { get; set; }
		public virtual System.Collections.Generic.ICollection<TelemetryViewModel> Telemetries { get; set; }
	}

	/// <summary>
	///
	/// A Telemetry view model
	///   
	///       MANUAL UPDATES REQUIRED! 
	///       NOTE use PM console to update database with new entity : 
	///            PM>add-migration AddTelemetry
	///            PM>update-database
	///
	/// </summary>
	public class TelemetryViewModel : BaseDomain
	{
		public string Ip { get; set; }
		public int ProductId { get; set; }
		public virtual ProductViewModel Product { get; set; }
		public int LicenseId { get; set; }
		public virtual LicenseViewModel License { get; set; }
		public int UserId { get; set; }
		public virtual UserViewModel User { get; set; }
	}

}