// <copyright file="5_t4ApiControllerGenerate.cs" company="marcos software">
// This file may not be redistributed in whole or significant part
// and is subject to the marcos software license.
//
// @author: Sascha Manns, s.manns@marcossoftware.com
// @copyright: 2022, marcos-software, http://www.marcos-software.de
// </copyright>



// —————————————— 
// <auto-generated> 
//	This code was auto-generated 07/18/2022 12:21:42 
//     	T4 template generates controller's code
//	NOTE:T4 generated code may need additional updates/addjustments by developer in order to compile a solution.
// <auto-generated> 
// —————————————–
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using AppLicenseserver.Domain;
using AppLicenseserver.Entity.Context;
using AppLicenseserver.Domain.Service;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;
using Serilog;
using AppLicenseserver.Entity;

namespace AppLicenseserver.Api.Controllers
{
}