// <copyright file="4_t4DomainServicesGenerate.cs" company="marcos software">
// This file may not be redistributed in whole or significant part
// and is subject to the marcos software license.
//
// @author: Sascha Manns, s.manns@marcossoftware.com
// @copyright: 2022, marcos-software, http://www.marcos-software.de
// </copyright>




// —————————————— 
// <auto-generated> 
//	This code was auto-generated 07/18/2022 12:21:38
//     	T4 template generates service code
//	NOTE:T4 generated code may need additional updates/addjustments by developer in order to compile a solution.
// <auto-generated> 
// —————————————–
using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Text;
using AutoMapper;
using AppLicenseserver.Entity;
using AppLicenseserver.Entity.UnitofWork;

namespace AppLicenseserver.Domain.Service
{
}